<a href="https://colab.research.google.com/github/arthurbarbosalima123-dot/projeto_final/blob/main/projeto_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from google import colab as cl
import pandas as pd
import plotly.graph_objects as go
import plotly.express as px

In [ ]:
file_upload = cl.files.upload()

Saving zomato.csv to zomato.csv

In [ ]:
df = pd.read_csv('zomato.csv')

In [ ]:
def clean_code(df):
    """ Esta funcao tem a responsabilidade de limpar o dataframe

        Tipos de limpeza:
        1. Remover a coluna Switch to order menu pois tem o mesmo valor em todas as linhas
        2. Remover as linhas duplicadas
        3. Remover as NaNs de todas as observações que possuem NaN em alguma variável

        Input: Dataframe
        Output: Dataframe
    """


    # 2. Remover as linhas duplicadas
    df = df.drop_duplicates()

    # 3. Remover as NaNs de todas as observações que possuem NaN em alguma variável
    df = df.dropna()

    return df

In [ ]:
# Preenchimento do nome dos países
COUNTRIES = {
1: "India",
14: "Australia",
30: "Brazil",
37: "Canada",
94: "Indonesia",
148: "New Zeland",
162: "Philippines",
166: "Qatar",
184: "Singapure",
189: "South Africa",
191: "Sri Lanka",
208: "Turkey",
214: "United Arab Emirates",
215: "England",
216: "United States of America",
}
def country_name(country_id):
  return COUNTRIES[country_id]

In [ ]:
# Criação do Tipo de Categoria de Comida
def create_price_type(price_range):
    if price_range == 1:
        return "cheap"
    elif price_range == 2:
        return "normal"
    elif price_range == 3:
        return "expensive"
    else:
        return "gourmet"

df['Price Category'] = df['Price range'].apply(create_price_type)

In [ ]:
# Definir cores por país:
country_colors ={
"India": 'yellow',
"Australia": 'darkblue',
"Brazil": 'green',
"Canada": 'red',
"Indonesia": 'orange',
"New Zeland": 'purple',
"Philippines": 'brown',
"Qatar": 'gray',
"Singapure": 'lightblue',
"South Africa": 'pink',
"Sri Lanka": 'darkgreen',
"Turkey": 'darkred',
"United Arab Emirates": 'goldenrod',
"England": 'lightgreen',
"United States of America": 'black',
}

In [ ]:
# Criação do nome das Cores

COLORS = {
    "3F7E00": "darkgreen",
    "5BA829": "green",
    "9ACD32": "lightgreen",
    "CDD614": "orange",
    "FFBA00": "red",
    "CBCBC8": "darkred",
    "FF7800": "darkred",
}
def color_name(color_code):
    return COLORS[color_code]

df['Color Name'] = df['Rating color'].apply(color_name)

In [ ]:
!pip install inflection
import inflection

def rename_columns(dataframe):
    df = dataframe.copy()
    title = lambda x: inflection.titleize(x)
    snakecase = lambda x: inflection.underscore(x)
    spaces = lambda x: x.replace(" ", "")
    cols_old = list(df.columns)
    cols_old = list(map(title, cols_old))
    cols_old = list(map(spaces, cols_old))
    cols_new = list(map(snakecase, cols_old))
    df.columns = cols_new
    return df

df = rename_columns(df)

Collecting inflection
  Downloading inflection-0.5.1-py2.py3-none-any.whl.metadata (1.7 kB)
Downloading inflection-0.5.1-py2.py3-none-any.whl (9.5 kB)
Installing collected packages: inflection
Successfully installed inflection-0.5.1

In [ ]:
# Limpando os dados
df = clean_code(df)

# Categorizar os restaurantes somente por um tipo de culinária:
df["cuisines"] = df.loc[:,"cuisines"].astype(str).apply(lambda x: x.split(",")[0])

# Criar uma nova coluna com os nomes dos países
df["Country"] = df["country_code"].apply(country_name)

#Removendo other em cuisines
df = df[df['cuisines'] != 'Other']

#Removendo Other
df = df[~df['cuisines'].isin(['Others', 'Unknown'])]

#Removendo India
df = df[df['Country'] != 'India']

#Removendo India
df = df[df['Country'] != 'Indonesia']

In [ ]:
total_culinaria = df['cuisines'].nunique()
print ('O Total de culinária é',total_culinaria)

O Total de culinária é 137

In [ ]:
pd.set_option('display.max_columns', None)

# País

---

1. Qual o nome do país que possui mais cidades registradas?

In [ ]:
df_city = df.loc[:,['city','Country']].groupby('Country').nunique().sort_values('city',ascending=False).df.head(7).reset_index()

px.bar (df_city, x='Country',y='city')

In [ ]:
# 2. Qual o nome do país que possui mais restaurantes registrados?
df_grafi = df.loc[:,['restaurant_id','Country']].groupby('Country').nunique().sort_values('restaurant_id',ascending=False).reset_index()

px.bar (df_grafi, x='Country',y='restaurant_id')

In [ ]:
# 3. Qual o nome do país que possui mais restaurantes com o nível de preço igual a 4 registrados?
restaurantes_preco_4 = df[df['price_range'] == 4]
restaurantes_preco_4.loc[:,['restaurant_id','Country']].groupby('Country').nunique().sort_values('restaurant_id',ascending=False).reset_index()

                     Country  restaurant_id
0   United States of America            415
1               South Africa            221
2                     Brazil            148
3       United Arab Emirates            102
4                 New Zeland             79
5                    England             79
6                     Turkey             59
7                  Singapure             58
8                     Canada             54
9                      Qatar             50
10                 Australia             33
11               Philippines             23
12                 Indonesia             17
13                 Sri Lanka             16

In [ ]:
# 4. Qual o nome do país que possui a maior quantidade de tipos de culinária distintos?
df.loc[:,['Country','cuisines']].groupby('Country').nunique().sort_values('cuisines',ascending=False).reset_index()

                     Country  cuisines
0   United States of America        74
1                    England        52
2       United Arab Emirates        46
3                  Australia        43
4                     Brazil        43
5               South Africa        42
6                     Canada        41
7                 New Zeland        37
8                      Qatar        31
9                     Turkey        28
10                 Sri Lanka        26
11                 Indonesia        21
12                 Singapure        21
13               Philippines        14

In [ ]:
# 5. Qual o nome do país que possui a maior quantidade de avaliações feitas?

df_avali =  df.loc[:,['Country','votes']].groupby('Country').mean().sort_values('votes',ascending=False).reset_index()

px.bar (df_avali, x='Country', y='votes')

In [ ]:
# 6. Qual o nome do país que possui a maior quantidade de restaurantes que fazem entrega?

restaurante_delivery = df[df['is_delivering_now'] == 1]
restaurante_delivery.loc[:,['Country','has_online_delivery']].groupby('Country').sum().sort_values('has_online_delivery',ascending=False).reset_index()

                Country  has_online_delivery
0                 India                 1150
1  United Arab Emirates                   52
2           Philippines                    7
3                 Qatar                    3

In [ ]:
# 7. Qual o nome do país que possui a maior quantidade de restaurantes que aceitam reservas?
df_reservas = df[df['has_table_booking'] == 1]
df_reservas.loc[:,['Country','has_table_booking']].groupby('Country').sum().sort_values('has_table_booking',ascending=False).reset_index()

                     Country  has_table_booking
0                      India                256
1                    England                 55
2                  Australia                 29
3                Philippines                 22
4                 New Zeland                 19
5                  Indonesia                 14
6       United Arab Emirates                 10
7                      Qatar                  4
8                     Turkey                  4
9               South Africa                  3
10  United States of America                  3
11                 Sri Lanka                  1

In [ ]:
# 8. Qual o nome do país que possui, na média, a maior quantidade de avaliações registrada?

df.loc[:,['Country','votes']].groupby('Country').mean().sort_values('votes',ascending=False).reset_index()

                     Country        votes
0                  Indonesia  1112.825000
1                      India   900.084860
2                  Australia   724.205556
3                     Turkey   630.144654
4                Philippines   604.975000
5       United Arab Emirates   591.880000
6                     Canada   583.433333
7   United States of America   380.165939
8                      Qatar   376.325000
9               South Africa   236.817919
10                New Zeland   219.799163
11                 Sri Lanka   151.662500
12                   England    99.890000
13                 Singapure    22.775000
14                    Brazil    12.404167

In [ ]:
# 9. Qual o nome do país que possui, na média, a maior nota média registrada?
df.loc[:, ['Country', 'aggregate_rating']] \
  .groupby('Country') \
  .mean() \
  .sort_values('aggregate_rating', ascending=False) \
  .reset_index()

                     Country  aggregate_rating
0                  Indonesia          4.601250
1                Philippines          4.463750
2                  Singapure          4.435000
3   United States of America          4.402693
4                  Australia          4.372778
5                     Canada          4.321667
6                     Turkey          4.310063
7                      Qatar          4.240000
8                 New Zeland          4.164435
9               South Africa          4.061561
10                 Sri Lanka          4.057500
11                   England          4.041750
12                     India          4.037126
13      United Arab Emirates          4.023667
14                    Brazil          3.321667

In [ ]:
# 10. Qual o nome do país que possui, na média, a menor nota média registrada?

df.loc[:, ['Country', 'aggregate_rating']] \
  .groupby('Country') \
  .mean() \
  .sort_values('aggregate_rating', ascending=True) \
  .reset_index()

                     Country  aggregate_rating
0                     Brazil          3.321667
1       United Arab Emirates          4.023667
2                      India          4.037126
3                    England          4.041750
4                  Sri Lanka          4.057500
5               South Africa          4.061561
6                 New Zeland          4.164435
7                      Qatar          4.240000
8                     Turkey          4.310063
9                     Canada          4.321667
10                 Australia          4.372778
11  United States of America          4.402693
12                 Singapure          4.435000
13               Philippines          4.463750
14                 Indonesia          4.601250

In [ ]:
# 11. Qual a média de preço de um prato para dois por país?

df_for_two = df.loc[:,['Country','average_cost_for_two']].groupby('Country').mean().sort_values('average_cost_for_two',ascending=False).reset_index()

px.bar (df_for_two, x='Country',y='average_cost_for_two')

# CIDADE

In [ ]:
df_city = df.loc[:,['city','Country','restaurant_id']].groupby(['city','Country']).nunique().sort_values('restaurant_id',ascending=False).head(10).reset_index()

# The line df_city['Color'] = df_city['Country'].map(country_colors) is no longer needed
# as px.bar can directly use the 'Country' column for coloring.

px.bar (df_city, x='city',y='restaurant_id', color='Country',color_discrete_map=country_colors,labels={
                     'City': 'Cidades',
                     'Restaurant Name': 'Quantidade de restaurantes',
                     'Country': 'País'
                 }, title='Top 10 Cidades com mais Restaurantes na Base de Dados',template='plotly_white')

In [ ]:
# 2. Qual o nome da cidade que possui mais restaurantes com nota média acima de 4?
avial_above_4 = df[df['aggregate_rating'] >= 4]
df_agg = avial_above_4.loc[:,['city','restaurant_id','Country']].groupby(['city','Country']).count().sort_values('restaurant_id',ascending=False).head(7).reset_index()

px.bar(df_agg, x='city',y='restaurant_id',color='Country', labels={
                     'city': 'Cidades',
                     'restaurant_id': 'Quantidade de restaurantes',
                     'Country': 'País'
                 }, title='Top 7 Cidades com mais Restaurantes com avaliação acima de 4',template='plotly_white')

In [ ]:
# 3. Qual o nome da cidade que possui mais restaurantes com nota média abaixo de 2.5
avali_under = df[df['aggregate_rating'] <=2.5]

df_under = avali_under.loc[:,['city','restaurant_id','Country']].groupby(['city','Country']).count().sort_values('restaurant_id',ascending=False).head(7).reset_index()

px.bar (df_under, x='city', y='restaurant_id', color = 'Country', labels={
                     'city': 'Cidades',
                     'restaurant_id': 'Quantidade de restaurantes',
                     'Country': 'País'
                 }, title='Top 7 Cidades com mais Restaurantes com avaliação abaixo de 2.5',template='plotly_dark')

In [ ]:
# 4. Qual o nome da cidade que possui o maior valor médio de um prato para dois?

df.loc[:,['city','average_cost_for_two']].groupby('city').mean().sort_values('average_cost_for_two',ascending=False).head(7).reset_index()

               city  average_cost_for_two
0          Adelaide         416734.133333
1        Pasay City           4000.000000
2           Colombo           2579.375000
3     Tagaytay City           1333.333333
4       Makati City           1308.823529
5       Taguig City           1247.222222
6  Mandaluyong City           1227.600000

In [ ]:
# 5. Qual o nome da cidade que possui a maior quantidade de tipos de culinária distintas?

df_culi = df.loc[:,['city','cuisines','Country']].groupby(['city','Country']).nunique().sort_values('cuisines',ascending=False).head(10).reset_index()

px.bar (df_culi, x='city',y='cuisines',color ='Country',title = 'Top 10 Cidades com mais restaurantes com tipos de culinários distintos',template = 'plotly_dark')

In [ ]:
#6. Qual o nome da cidade que possui a maior quantidade de restaurantes que fazem reservas?
df_reservas = df[df['has_table_booking'] == 1]
df_reservas.loc[:,['city','has_table_booking']].groupby('city').sum().sort_values('has_table_booking',ascending=False).head(10).reset_index()

        city  has_table_booking
0  Bangalore                 42
1    Chennai                 28
2       Pune                 25
3     Mumbai                 18
4   Brisbane                 17
5   Auckland                 17
6  New Delhi                 16
7     London                 15
8    Jakarta                 13
9  Edinburgh                 13

In [ ]:
#7. Qual o nome da cidade que possui a maior quantidade de restaurantes que fazem entregas?
delivery = df[df['is_delivering_now'] == 1]
delivery.loc [:,['city','is_delivering_now']].groupby('city').sum().sort_values('is_delivering_now',ascending=False).reset_index()

            city  is_delivering_now
0       Amritsar                 48
1       Vadodara                 48
2     Aurangabad                 47
3       Ludhiana                 46
4         Bhopal                 46
5       Dehradun                 45
6         Ranchi                 42
7         Jaipur                 42
8      Ahmedabad                 41
9       Varanasi                 40
10        Indore                 40
11       Lucknow                 38
12        Nagpur                 37
13          Agra                 36
14        Kanpur                 35
15    Chandigarh                 33
16     Allahabad                 31
17         Surat                 31
18  Bhubaneshwar                 31
19         Patna                 29
20    Coimbatore                 28
21        Mysore                 28
22     Mangalore                 28
23        Nashik                 27
24     Abu Dhabi                 26
25         Vizag                 25
26          Ooty                 22
27    Puducherry                 22
28        Mumbai                 21
29     New Delhi                 19
30         Kochi                 19
31          Pune                 18
32      Guwahati                 18
33       Kolkata                 17
34       Chennai                 16
35       Sharjah                 14
36     Hyderabad                 14
37        Mohali                 13
38         Dubai                 12
39     Bangalore                  9
40   Taguig City                  5
41           Goa                  4
42       Gurgaon                  4
43     Panchkula                  4
44          Doha                  3
45         Nasik                  2
46   Makati City                  2
47  Secunderabad                  2
48         Noida                  2
49   Gandhinagar                  1
50         Thane                  1

In [ ]:
# 8. Qual o nome da cidade que possui a maior quantidade de restaurantes que aceitam pedidos online?
df_delivery = df[df['has_online_delivery']==1]
df_delivery.loc[:,['city','has_online_delivery']].groupby('city').sum().sort_values('has_online_delivery',ascending=False).head(10).reset_index()

         city  has_online_delivery
0      Bhopal                   75
1    Vadodara                   74
2   Abu Dhabi                   71
3     Sharjah                   71
4  Aurangabad                   69
5       Patna                   69
6      Nagpur                   69
7      Ranchi                   69
8   Allahabad                   68
9  Coimbatore                   68

# Restaurantes

In [ ]:
# 1. Qual o nome do restaurante que possui a maior quantidade de avaliações?

df.loc[:,['restaurant_name','votes']].groupby('restaurant_name').sum().sort_values('votes',ascending=False).head(7).reset_index()

             restaurant_name  votes
0             Domino's Pizza  59749
1  AB's - Absolute Barbecues  58875
2            Barbeque Nation  53200
3                   Bawarchi  41711
4                   Paradise  38283
5                        KFC  29473
6        Chili's Grill & Bar  27689

In [ ]:
df.columns

Index(['restaurant_id', 'restaurant_name', 'country_code', 'city', 'address',
       'locality', 'locality_verbose', 'longitude', 'latitude', 'cuisines',
       'average_cost_for_two', 'currency', 'has_table_booking',
       'has_online_delivery', 'is_delivering_now', 'switch_to_order_menu',
       'price_range', 'aggregate_rating', 'rating_color', 'rating_text',
       'votes', 'price_category', 'color_name', 'Country'],
      dtype='object')

In [ ]:
# 2. Qual o nome do restaurante com a maior nota média?
df.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head(7).reset_index()

                 restaurant_name  aggregate_rating
0                        Hodad's               4.9
1  Zolocrust - Hotel Clarks Amer               4.9
2                          Ombra               4.9
3                         Colony               4.9
4                        Baithak               4.9
5            The Parlor Pizzeria               4.9
6               The Potluck Club               4.9

In [ ]:
#3. Qual o nome do restaurante que possui o maior valor de uma prato para duas pessoas?
df.loc[:,['restaurant_name','average_cost_for_two']].groupby('restaurant_name').sum().sort_values('average_cost_for_two',ascending=False).head(7).reset_index()

                restaurant_name  average_cost_for_two
0  d'Arry's Verandah Restaurant              25000017
1       Gyu - Kaku Japanese BBQ               3150000
2                    Sushi Hiro               2000000
3        The Café - Hotel Mulia               1200000
4         Magal Mapogalmegi BBQ                900000
5          GIA Restaurant & Bar                700000
6                   Shabu Hachi                700000

In [ ]:
# 4. Qual o nome do restaurante de tipo de culinária brasileira que possui a menor média de avaliação?

df_culinaria = df[df['cuisines']=='Brazilian']
df_culinaria.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=True).head(50).reset_index()

               restaurant_name  aggregate_rating
0        Bar do Luiz Fernandes              0.00
1                      Barbosa              0.00
2             Cantinho da Gula              0.00
3                  Café Savana              0.00
4             Famiglia Rivitti              0.00
5             Capricho Mineiro              0.00
6           Inácia Poulet Rôti              0.00
7           Tempero das Gerais              0.00
8                     Quitéria              0.00
9                   Rancho Inn              0.00
10      Restaurante dos Amigos              0.00
11                    Severina              0.00
12          Loca Como tu Madre              0.00
13  NAVE MÃE FAST FOOD GOURMET              0.00
14        Galeteria Beira Lago              0.00
15           Café das Estrelas              3.00
16                  Liv Lounge              3.30
17     Confraria Chico Mineiro              3.30
18                       Maori              3.60
19                 Viva Brazil              3.60
20             Bierfass Pontão              3.70
21         Botequim Cachambeer              3.90
22                    Mocellin              4.00
23                  Leme Light              4.10
24            Camarada Camarão              4.10
25             Gaia Art & Cafe              4.20
26                   Monchique              4.20
27           Bolero Fire Grill              4.20
28           Gaucho Steakhouse              4.20
29             Santo Scenarium              4.20
30                Café do Alto              4.30
31         Academia da Cachaça              4.30
32                         Oro              4.30
33                  Bem Brasil              4.30
34            Bar da Dona Onça              4.40
35                     Paribar              4.40
36                    Insalata              4.40
37                 Rei do Gado              4.40
38                      Stalos              4.40
39                 Marisqueira              4.40
40                Dalva e Dito              4.40
41                     Estadão              4.40
42             Boteco Belmonte              4.40
43                Filé de Ouro              4.40
44            Casa da Feijoada              4.40
45            Chima Steakhouse              4.40
46                  Balada Mix              4.45
47              Bar do Mineiro              4.50
48          Giuseppe Grill Mar              4.50
49                    Bar Urca              4.50

In [ ]:
#5. Qual o nome do restaurante de tipo de culinária brasileira, e que é do Brasil, que possui a maior média de avaliação?
df_culinaria = df[(df['cuisines']=='Brazilian') & (df['Country']=='Brazil')]
df_culinaria.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head(10).reset_index()

        restaurant_name  aggregate_rating
0             Aprazível              4.90
1     Braseiro da Gávea              4.90
2          Fogo de Chão              4.80
3                Mocotó              4.80
4     Aconchego Carioca              4.70
5  Zazá Bistrô Tropical              4.70
6                Veloso              4.60
7     Garota de Ipanema              4.55
8    Giuseppe Grill Mar              4.50
9        Bar do Mineiro              4.50

In [ ]:
#6. Os restaurantes que aceitam pedido online são também, na média, os restaurantes que mais possuem avaliações registradas?

df.loc[:,['has_online_delivery','votes']].groupby('has_online_delivery').mean().sort_values('votes',ascending=False).reset_index()

   has_online_delivery       votes
0                    1  838.821664
1                    0  479.421018

# Tipos de Culinária

In [ ]:
#1. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a maior média de avaliação?

italian_cuisines = df[df['cuisines'] =='Italian']
italian_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head().reset_index()

       restaurant_name  aggregate_rating
0  The Parlor Pizzeria               4.9
1           Big Bill's               4.9
2        Bottega Louie               4.9
3      Regina Pizzeria               4.9
4      Central Grocery               4.9

In [ ]:
top10 = (
    df.loc[:, [
        'restaurant_id',
        'restaurant_name',
        'Country',
        'city',
        'cuisines',
        'average_cost_for_two',
        'aggregate_rating',
        'votes'
    ]]
    .sort_values('aggregate_rating', ascending=False)
    .head(10)
)

In [ ]:
df_best = (
    df.loc[:, ['cuisines', 'restaurant_name', 'aggregate_rating']]
       .sort_values('aggregate_rating', ascending=False)
       .groupby('cuisines')
       .first()
       .reset_index()
)
df_best

          cuisines                     restaurant_name  aggregate_rating
0          African                               Kream               4.8
1         American                           Cafe Muse               4.9
2          Arabian                  Madfoon Al Khaimah               4.5
3        Argentine                   Gaucho Manchester               4.4
4            Asian                                Kazu               4.9
..             ...                                 ...               ...
132      Ukrainian                             Veselka               4.6
133     Vegetarian                      Lola Rosa Cafe               4.7
134     Vietnamese  Vietnam House Restaurant & Gallery               4.9
135  World Cuisine                        Gaga Manjero               4.9
136        Yum Cha  Dragon Palace & Karaoke Restaurant               3.9

[137 rows x 3 columns]

In [ ]:

brazilian_cuisines = df[df['cuisines'] =='Brazilian']
brazilian_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head().reset_index()

         restaurant_name  aggregate_rating
0              Aprazível               4.9
1      Braseiro da Gávea               4.9
2  Ola Brasil Restaurant               4.9
3           Fogo de Chão               4.8
4                 Mocotó               4.8

In [ ]:
#2. Dos restaurantes que possuem o tipo de culinária italiana, qual o nome do restaurante com a menor média de avaliação?
italian_cuisines = df[df['cuisines'] =='Italian']
italian_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=True).head(5).reset_index()

             restaurant_name  aggregate_rating
0                      Veeno               0.0
1           Avenida Paulista               0.0
2               Ristorantino               0.0
3   La Bocca Bar e Trattoria               0.0
4  Bene - Sheraton Rio Hotel               0.0

In [ ]:
#3. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a maior média de avaliação?

american_cuisines = df[df['cuisines']=='American']
american_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head(5).reset_index()

             restaurant_name  aggregate_rating
0        Portillo's Hot Dogs               4.9
1  The Magnolia Pancake Haus               4.9
2                  Cafe Muse               4.9
3            Brick Store Pub               4.9
4          OEB Breakfast Co.               4.9

In [ ]:
#4. Dos restaurantes que possuem o tipo de culinária americana, qual o nome do restaurante com a menor média de avaliação?
american_cuisines = df[df['cuisines']=='American']
american_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=True).head(5).reset_index()

             restaurant_name  aggregate_rating
0          Alston Bar & Beef               0.0
1  Guy Fieri's Kitchen & Bar               2.2
2                      Bob's               2.6
3           Thunderbird Cafe               3.2
4                Lava Lounge               3.3

In [ ]:
#5. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a maior média de avaliação?
arabia_cuisines = df[df['cuisines']=='Arabian']
arabia_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head(5).reset_index()

      restaurant_name  aggregate_rating
0  Madfoon Al Khaimah               4.5
1         Wok of Fame               4.5
2      Aroos Damascus               4.4
3           Azkadenya               4.3
4               Awani               4.2

In [ ]:
#6. Dos restaurantes que possuem o tipo de culinária árabe, qual o nome do restaurante com a menor média de avaliação?

arabia_cuisines = df[df['cuisines']=='Arabian']
arabia_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=True).head(5).reset_index()

    restaurant_name  aggregate_rating
0             Raful               0.0
1     Empório Árabe               2.7
2      Salim Sou Eu               3.1
3  Abad Hot Chicken               3.2
4         V Empire                3.2

In [ ]:
#7. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a maior média de avaliação?
japao_cuisines = df[df['cuisines']=='Japanese']
japao_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head(5).reset_index()

            restaurant_name  aggregate_rating
0              Chotto Matte               4.9
1              Sushi Leblon               4.9
2               Sushi Samba               4.9
3  WAKI Japanese BBQ Dining               4.9
4         Mendokoro Ramenba               4.9

In [ ]:
#8. Dos restaurantes que possuem o tipo de culinária japonesa, qual o nome do restaurante com a menor média de avaliação?
japao_cuisines = df[df['cuisines']=='Japanese']
japao_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=True).head(5).reset_index()

  restaurant_name  aggregate_rating
0    Banzai Sushi               0.0
1       Orienthai               2.4
2         Hachiko               2.5
3            Haná               2.7
4      Sushi Loko               2.9

In [ ]:
#9. Dos restaurantes que possuem o tipo de culinária caseira, qual o nome do restaurante com a maior média de avaliação?
caseira_cuisines = df[df['cuisines']=='Home-made']
caseira_cuisines.loc[:,['restaurant_name','aggregate_rating']].groupby('restaurant_name').mean().sort_values('aggregate_rating',ascending=False).head().reset_index()

       restaurant_name  aggregate_rating
0     Kanaat Lokantası               4.0
1  GurMekan Restaurant               3.7

In [ ]:
#11. Qual o tipo de culinária que possui o maior valor médio de um prato para duas pessoas?
df.loc[:,['cuisines','average_cost_for_two']].groupby('cuisines').mean().sort_values('average_cost_for_two',ascending=False).head().reset_index()

            cuisines  average_cost_for_two
0  Modern Australian          1.470693e+06
1            Western          3.333333e+05
2         Indonesian          2.000000e+05
3              Sunda          2.000000e+05
4             Dimsum          1.500000e+05

In [ ]:
# 12. Qual o tipo de culinária que possui a maior nota média?

df_top_10 = df.loc[:, ['cuisines','aggregate_rating']] .groupby('cuisines').mean() .sort_values('aggregate_rating', ascending=False) .head(10).reset_index()

px.bar (df_top_10, x ='cuisines', y='aggregate_rating')

In [ ]:
# 12. Qual o tipo de culinária que possui a pior nota média?

pior_avaliacao = df[df['aggregate_rating'] >0.000000]

df_pior = pior_avaliacao.loc[:, ['cuisines','aggregate_rating']] .groupby('cuisines').mean() .sort_values('aggregate_rating', ascending=True).head(10) .reset_index()

px.bar (df_pior, x='cuisines',y='aggregate_rating')

In [ ]:
#13. Qual o tipo de culinária que possui mais restaurantes que aceitam pedidos online e fazem entregas?
# Filter the DataFrame for restaurants that have online delivery AND are delivering now
filtered_restaurants = df[(df['has_online_delivery'] == 1) & (df['is_delivering_now'] == 1)]

# Group by cuisines and count the number of restaurants
filtered_restaurants.groupby('cuisines')['restaurant_id'].count().sort_values(ascending=False).head(10).reset_index()

       cuisines  restaurant_id
0        Indian             19
1      Lebanese             10
2         Pizza              4
3      American              4
4     Fast Food              4
5          Cafe              3
6  Healthy Food              3
7   Street Food              3
8       Arabian              2
9  South Indian              2

In [ ]:
melhores_restaurantes = df[df['aggregate_rating']==df['aggregate_rating'].max()]
melhores_restaurantes.head(5)

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,average_cost_for_two,currency,has_table_booking,has_online_delivery,is_delivering_now,switch_to_order_menu,price_range,aggregate_rating,rating_color,rating_text,votes,price_category,color_name,Country
17,6316125,Mendokoro Ramenba,162,Makati City,"V. Corporate Center, Soliman Street, Salcedo V...",Salcedo Village,"Salcedo Village, Makati City",121.024663,14.560227,Japanese,1000,Botswana Pula(P),0,0,0,0,3,4.9,3F7E00,Excellent,1832,expensive,darkgreen,Philippines
21,6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056101,14.583759,Japanese,1500,Botswana Pula(P),0,0,0,0,4,4.9,3F7E00,Excellent,1167,gourmet,darkgreen,Philippines
32,6309831,Ramen Yushoken,162,Muntinlupa City,"Molito Commercial Complex, Alabang, Muntinlupa...","Molito Commercial Complex, Alabang, Mutinlupa ...","Molito Commercial Complex, Alabang, Mutinlupa ...",121.026947,14.424748,Japanese,800,Botswana Pula(P),0,0,0,0,3,4.9,3F7E00,Excellent,1171,expensive,darkgreen,Philippines
34,6300010,Spiral - Sofitel Philippine Plaza Manila,162,Pasay City,"Plaza Level, Sofitel Philippine Plaza Manila, ...","Sofitel Philippine Plaza Manila, CCP Complex, ...","Sofitel Philippine Plaza Manila, CCP Complex, ...",120.981666,14.552857,European,6000,Botswana Pula(P),0,0,0,0,4,4.9,3F7E00,Excelente,1228,gourmet,darkgreen,Philippines
41,6309903,Silantro Fil-Mex,162,Pasig City,"75 East Capitol Drive, Kapitolyo, Pasig City",Kapitolyo,"Kapitolyo, Pasig City",121.057860,14.567676,Filipino,800,Botswana Pula(P),0,0,0,0,3,4.9,3F7E00,Excellent,1544,expensive,darkgreen,Philippines

In [ ]:
rest_uni = df.loc[:,'restaurant_id'].nunique()
rest_uni

3737

In [ ]:
pais_uni = df.loc[:,'Country'].nunique()
pais_uni

13

In [ ]:
cid = df.loc[:,'city'].nunique()
cid

73

In [ ]:
total_avaliacao = df['votes'].sum()
total_avaliacao

np.int64(1304642)

In [ ]:
df.head()

,restaurant_id,restaurant_name,country_code,city,address,locality,locality_verbose,longitude,latitude,cuisines,...,is_delivering_now,switch_to_order_menu,price_range,aggregate_rating,rating_color,rating_text,votes,price_category,color_name,Country
0,6310675,Mama Lou's Italian Kitchen,162,Las Piñas City,"Block 1, Lot 36, Tropical Avenue Corner Tropic...",BF International,"BF International, Las Piñas City",121.009787,14.447615,Italian,...,0,0,3,4.6,3F7E00,Excellent,619,expensive,darkgreen,Philippines
2,6314542,Blackbird,162,Makati City,"Nielson Tower, Ayala Triangle Gardens, Salcedo...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.024562,14.556042,European,...,0,0,4,4.7,3F7E00,Excellent,469,gourmet,darkgreen,Philippines
3,6301293,Banapple,162,Makati City,"Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...","Ayala Triangle Gardens, Salcedo Village, Makat...",121.023171,14.556196,Filipino,...,0,0,3,4.4,5BA829,Very Good,867,expensive,green,Philippines
4,6315689,Bad Bird,162,Makati City,"Hole In The Wall, Floor 4, Century City Mall, ...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027708,14.565899,American,...,0,0,3,4.4,5BA829,Very Good,858,expensive,green,Philippines
5,6304833,Manam,162,Makati City,"Level 1, Greenbelt 2, Ayala Center, Greenbelt,...","Greenbelt 2, San Lorenzo, Makati City","Greenbelt 2, San Lorenzo, Makati City, Makati ...",121.020380,14.552351,Filipino,...,0,0,3,4.7,3F7E00,Excellent,930,expensive,darkgreen,Philippines